In [1]:
# The following notebook looks at null data
# the pain for any DS is what to do with missing data. Can be missing for a variety of reasons.
# we first need to be able to identify and mark missing data .
# we then need to know what ot do with it. Replace it with some value , if which case what value
# or remove it outright ?

In [2]:
# we begin with using diabetes data set 

In [57]:
import pandas as pd
df_raw_data = pd.read_csv('https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.csv', header = None)

In [36]:
df_raw_data.shape

(768, 9)

In [37]:
df_raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       768 non-null    int64  
 1   1       768 non-null    int64  
 2   2       768 non-null    int64  
 3   3       768 non-null    int64  
 4   4       768 non-null    int64  
 5   5       768 non-null    float64
 6   6       768 non-null    float64
 7   7       768 non-null    int64  
 8   8       768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [38]:
df_raw_data.head(3)

0    1   2   3  4     5      6   7  8
0  6  148  72  35  0  33.6  0.627  50  1
1  1   85  66  29  0  26.6  0.351  31  0
2  8  183  64   0  0  23.3  0.672  32  1

In [39]:
df_raw_data.nunique()

0     17
1    136
2     47
3     51
4    186
5    248
6    517
7     52
8      2
dtype: int64

In [40]:
df_raw_data.describe()

0           1           2           3           4           5  \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000   
mean     3.845052  120.894531   69.105469   20.536458   79.799479   31.992578   
std      3.369578   31.972618   19.355807   15.952218  115.244002    7.884160   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   23.000000   30.500000   32.000000   
75%      6.000000  140.250000   80.000000   32.000000  127.250000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

                6           7           8  
count  768.000000  768.000000  768.000000  
mean     0.471876   33.240885    0.348958  
std      0.331329   11.760232    0.476951  
min      0.078000   21.000000    0.000000  
25%      0.243750   24.000000    0.000000  
50%      0.372500   29.000000    0.000000  
75%      0.626250   41.000000    1.000000  
max      2.420000   81.000000    1.000000

In [41]:
df_raw_data.head(4)

0    1   2   3   4     5      6   7  8
0  6  148  72  35   0  33.6  0.627  50  1
1  1   85  66  29   0  26.6  0.351  31  0
2  8  183  64   0   0  23.3  0.672  32  1
3  1   89  66  23  94  28.1  0.167  21  0

In [42]:
# column 8 is the target varialbe -> boolean/catergorail. If someone has diabetes or not

In [43]:
# The following shows a way of displaying all values in columns which are equal to 0 

In [44]:
(df_raw_data[[0,1,2,3,4,5]]==0).sum()

0    111
1      5
2     35
3    227
4    374
5     11
dtype: int64

In [45]:
# from the above some column have many values set as zero while others less so. 
df_raw_data.shape[0]

768

In [46]:
# almost half of column 4 is zero 
374/768

0.4869791666666667

In [58]:
import numpy as np 

df_raw_data[[0,1,2,3,4,5]] = df_raw_data[[0,1,2,3,4,5]].replace(0,np.nan)

In [61]:
df_raw_data.isnull().sum()

0    111
1      5
2     35
3    227
4    374
5     11
6      0
7      0
8      0
dtype: int64

In [63]:
df_raw_data.dropna().shape

(336, 9)

In [64]:
# above we removed rows which had nan . But can we do better?

In [70]:
df_raw_data.isnull().sum()/df_raw_data.shape[0]

0    0.144531
1    0.006510
2    0.045573
3    0.295573
4    0.486979
5    0.014323
6    0.000000
7    0.000000
8    0.000000
dtype: float64

In [69]:
df_raw_data.shape[0]

768

In [150]:
df_horse_data = pd.read_csv('https://raw.githubusercontent.com/jbrownlee/Datasets/master/horse-colic.csv',header =None, na_values='?')

In [73]:
df_horse_data.shape

(300, 28)

In [74]:
df_horse_data.describe()

1             2           23            24           25  \
count  300.000000  3.000000e+02  300.000000    300.000000   300.000000   
mean     1.640000  1.085889e+06    1.363333   3657.880000    90.226667   
std      2.173972  1.529801e+06    0.481763   5399.513513   649.569234   
min      1.000000  5.184760e+05    1.000000      0.000000     0.000000   
25%      1.000000  5.289040e+05    1.000000   2111.750000     0.000000   
50%      1.000000  5.303055e+05    1.000000   2673.500000     0.000000   
75%      1.000000  5.347275e+05    2.000000   3209.000000     0.000000   
max      9.000000  5.305629e+06    2.000000  41110.000000  7111.000000   

                26          27  
count   300.000000  300.000000  
mean      7.363333    1.670000  
std     127.536674    0.470998  
min       0.000000    1.000000  
25%       0.000000    1.000000  
50%       0.000000    2.000000  
75%       0.000000    2.000000  
max    2209.000000    2.000000

In [75]:
df_horse_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 28 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       300 non-null    object
 1   1       300 non-null    int64 
 2   2       300 non-null    int64 
 3   3       300 non-null    object
 4   4       300 non-null    object
 5   5       300 non-null    object
 6   6       300 non-null    object
 7   7       300 non-null    object
 8   8       300 non-null    object
 9   9       300 non-null    object
 10  10      300 non-null    object
 11  11      300 non-null    object
 12  12      300 non-null    object
 13  13      300 non-null    object
 14  14      300 non-null    object
 15  15      300 non-null    object
 16  16      300 non-null    object
 17  17      300 non-null    object
 18  18      300 non-null    object
 19  19      300 non-null    object
 20  20      300 non-null    object
 21  21      300 non-null    object
 22  22      300 non-null    ob

In [78]:
df_horse_data.head()

0   1        2      3    4   5  6  7  8  9   ...     18    19 20    21 22  \
0  2   1   530101  38.50   66  28  3  3  ?  2  ...  45.00  8.40  ?     ?  2   
1  1   1   534817   39.2   88  20  ?  ?  4  1  ...     50    85  2     2  3   
2  2   1   530334  38.30   40  24  1  1  3  1  ...  33.00  6.70  ?     ?  1   
3  1   9  5290409  39.10  164  84  4  1  6  2  ...  48.00  7.20  3  5.30  2   
4  2   1   530255  37.30  104  35  ?  ?  6  2  ...  74.00  7.40  ?     ?  2   

  23     24 25 26 27  
0  2  11300  0  0  2  
1  2   2208  0  0  2  
2  2      0  0  0  1  
3  1   2208  0  0  1  
4  2   4300  0  0  2  

[5 rows x 28 columns]

In [146]:
df_horse_data.replace('?',np.nan,inplace=True)

In [82]:
df_horse_data.isnull().any()

0      True
1     False
2     False
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21     True
22     True
23    False
24    False
25    False
26    False
27    False
dtype: bool

In [89]:
df_horse_data[4].isnull().sum()

24

In [92]:
for i in range(df_horse_data.shape[1]):
    print (i ,df_horse_data[i].isnull().sum(), (df_horse_data[i].isnull().sum()/df_horse_data[i].count())*100)

0 1 0.33444816053511706
1 0 0.0
2 0 0.0
3 60 25.0
4 24 8.695652173913043
5 58 23.96694214876033
6 56 22.950819672131146
7 69 29.87012987012987
8 47 18.57707509881423
9 32 11.940298507462686
10 55 22.448979591836736
11 44 17.1875
12 56 22.950819672131146
13 104 53.06122448979592
14 106 54.63917525773196
15 247 466.03773584905656
16 102 51.515151515151516
17 118 64.83516483516483
18 29 10.70110701107011
19 33 12.359550561797752
20 165 122.22222222222223
21 198 194.11764705882354
22 1 0.33444816053511706
23 0 0.0
24 0 0.0
25 0 0.0
26 0 0.0
27 0 0.0


In [157]:
# we can use SimpleImputer 
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from numpy import isnan

df_horse_data = pd.read_csv('https://raw.githubusercontent.com/jbrownlee/Datasets/master/horse-colic.csv',header =None, na_values='?')

X = df_horse_data.drop([13],axis=1)
y = df_horse_data[13]
print(X.shape, y.shape)

data = df_horse_data.values
ix = [i for i in range(data.shape[1]) if i != 23]
X, y = data[:, ix], data[:, 23]

(300, 27) (300,)


In [158]:
X

array([[2.00000e+00, 1.00000e+00, 5.30101e+05, ..., 0.00000e+00,
        0.00000e+00, 2.00000e+00],
       [1.00000e+00, 1.00000e+00, 5.34817e+05, ..., 0.00000e+00,
        0.00000e+00, 2.00000e+00],
       [2.00000e+00, 1.00000e+00, 5.30334e+05, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00],
       ...,
       [1.00000e+00, 1.00000e+00, 5.29386e+05, ..., 0.00000e+00,
        0.00000e+00, 2.00000e+00],
       [1.00000e+00, 1.00000e+00, 5.30612e+05, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00],
       [1.00000e+00, 1.00000e+00, 5.34618e+05, ..., 0.00000e+00,
        0.00000e+00, 2.00000e+00]])

In [159]:
SI= SimpleImputer(strategy = 'mean')
RF = RandomForestClassifier()
pipeline = Pipeline(steps = [('SI', SI), ('RF',RF)])

RS = RepeatedStratifiedKFold(n_splits =5, n_repeats =3, random_state =42)



print(X)
CVS = cross_val_score(pipeline, X , y, scoring = 'accuracy', cv = RS)

[[2.00000e+00 1.00000e+00 5.30101e+05 ... 0.00000e+00 0.00000e+00
  2.00000e+00]
 [1.00000e+00 1.00000e+00 5.34817e+05 ... 0.00000e+00 0.00000e+00
  2.00000e+00]
 [2.00000e+00 1.00000e+00 5.30334e+05 ... 0.00000e+00 0.00000e+00
  1.00000e+00]
 ...
 [1.00000e+00 1.00000e+00 5.29386e+05 ... 0.00000e+00 0.00000e+00
  2.00000e+00]
 [1.00000e+00 1.00000e+00 5.30612e+05 ... 0.00000e+00 0.00000e+00
  1.00000e+00]
 [1.00000e+00 1.00000e+00 5.34618e+05 ... 0.00000e+00 0.00000e+00
  2.00000e+00]]


In [166]:
np.mean(CVS)

0.8622222222222221

In [160]:
X = [[np.nan, 2, 3], [4, np.nan, 6], [10, np.nan, 9]]

In [161]:
type(X)

list

In [162]:
SI.fit_transform(X)

array([[ 7.,  2.,  3.],
       [ 4.,  2.,  6.],
       [10.,  2.,  9.]])

In [164]:
SI.fit_transform(pd.DataFrame(X))

array([[ 7.,  2.,  3.],
       [ 4.,  2.,  6.],
       [10.,  2.,  9.]])

In [172]:
X = df_horse_data.drop([23],axis=1)
y = df_horse_data[23]

In [173]:
CVS = cross_val_score(pipeline, X , y, scoring = 'accuracy', cv = RS)

In [174]:
# consider using many strategies 
strag = ['mean', 'median','most_frequent','constant']


for s in strag:
    SI= SimpleImputer(strategy = 'mean')
    RF = RandomForestClassifier()
    pipeline = Pipeline(steps = [('SI', SI), ('RF',RF)])

    RS = RepeatedStratifiedKFold(n_splits =5, n_repeats =3, random_state =42)
    CVS = cross_val_score(pipeline, X , y, scoring = 'accuracy', cv = RS)
    
    print(s, np.mean(CVS), np.std(CVS))

mean 0.8666666666666667 0.03990729999126216
median 0.8722222222222221 0.0337016686402291
most_frequent 0.8666666666666667 0.032203059435976525
constant 0.86 0.02968975381308307


In [175]:
# What have we covered in this notebook
# learnt how to mark missing values and how they can be replaced with statistical measures 
# how to load a csv and mark directly missing values
# how to use pipeline to replace nan with SimpleImputer
# how to use different models when predicting values 